




-- 用户信息表
CREATE TABLE TOP_USERINFO (
  USER_ID	VARCHAR2(32) primary key NOT NULL,
  LOGIN_ACCOUNT	VARCHAR2(20)	NOT NULL,
  LOGIN_PWD	VARCHAR2(32) NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  USER_LEVEL VARCHAR2(20),
  USER_DEPT VARCHAR2(20) NOT NULL,
  USER_STATUS CHAR(1) NOT NULL,
  ISREVIEW CHAR(1) NOT NULL,
  CREATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_TIME VARCHAR2(6) NOT NULL,
  UPDATE_OPERATOR VARCHAR2(8) NOT NULL,
  SALT varchar2(60),
  FILE_PATH VARCHAR2(60),
  REMARK1 VARCHAR2(60),
  REMARK2 VARCHAR2(60),
  REMARK3 VARCHAR2(60),
  REMARK4 VARCHAR2(60),
  REMARK5 VARCHAR2(60)
);
    
-- 角色信息表
CREATE TABLE TOP_ROLEINFO (
  ROLE_ID  VARCHAR2(32) primary key NOT NULL,
  ROLE_CODE  VARCHAR2(8)  NOT NULL,
  ROLE_NAME  VARCHAR2(60) NOT NULL,
  DESCRIPTION VARCHAR2(150),
  ISREVIEW CHAR(1) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  CREATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_TIME VARCHAR2(6) NOT NULL,
  UPDATE_OPERATOR VARCHAR2(8) NOT NULL,
  REMARK1 VARCHAR2(60),
  REMARK2 VARCHAR2(60),
  REMARK3 VARCHAR2(60),
  REMARK4 VARCHAR2(60),
  REMARK5 VARCHAR2(60)
) ;

-- Create table
create table TOP_BANKINFO
(
  bank_code         VARCHAR2(20) primary key not null,
  bank_name         VARCHAR2(60) not null,
  bank_level        VARCHAR2(1) not null,
  up_bankcode       VARCHAR2(20) not null,
  admin_flag        VARCHAR2(1) not null,
  address           VARCHAR2(60),
  postcode          VARCHAR2(60),
  phone             VARCHAR2(20),
  fax               VARCHAR2(20),
  status            VARCHAR2(1),
  operator_bankcode VARCHAR2(20) not null,
  operator_code     VARCHAR2(20) not null,
  updatedate        VARCHAR2(20) not null,
  updatetime        VARCHAR2(20) not null,
  certno            VARCHAR2(30),
  certenddate       VARCHAR2(8),
  certstartdate     VARCHAR2(8)
);

-- 菜单信息表
CREATE TABLE TOP_MENUINFO (
  MENU_ID  VARCHAR2(32) primary key NOT NULL,
  MENU_CODE  VARCHAR2(8)  NOT NULL,
  FA_MENU_CODE  VARCHAR2(8) NOT NULL,
  MENU_NAME VARCHAR2(60) NOT NULL,
  MENU_URL VARCHAR2(200) ,
  STATUS CHAR(1) NOT NULL,
  CREATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_TIME VARCHAR2(6) NOT NULL,
  UPDATE_OPERATOR VARCHAR2(8) NOT NULL,
  ICON	VARCHAR2(40),
  BELONG_SYSTEM VARCHAR2(10),
  REMARK1 VARCHAR2(60),
  REMARK2 VARCHAR2(60),
  REMARK3 VARCHAR2(60),
  REMARK4 VARCHAR2(60),
  REMARK5 VARCHAR2(60)
);


-- 用户角色关系表
CREATE TABLE TOP_USER_ROLE (
  USER_ID  VARCHAR2(32)  NOT NULL,
  ROLE_ID  VARCHAR2(32)  NOT NULL,
  CREATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_OPERATOR VARCHAR2(8) NOT NULL,
  REMARK1 VARCHAR2(60),
  REMARK2 VARCHAR2(60),
  REMARK3 VARCHAR2(60),
  REMARK4 VARCHAR2(60),
  REMARK5 VARCHAR2(60)
);

-- 角色菜单关系表
CREATE TABLE TOP_TASK_MENU (
  ROLE_ID  VARCHAR2(32)  NOT NULL,
  MENU_ID  VARCHAR2(32)  NOT NULL,
  CREATE_DATE VARCHAR2(8) NOT NULL,
  UPDATE_OPERATOR VARCHAR2(8) NOT NULL,
  REMARK1 VARCHAR2(60),
  REMARK2 VARCHAR2(60),
  REMARK3 VARCHAR2(60),
  REMARK4 VARCHAR2(60),
  REMARK5 VARCHAR2(60)
);


